global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:1993']
  - job_name: 'rabbitmq'
    scrape_interval: 5s
    static_configs:
      - targets: ['rabbitmq:15692']
